version: "3.7"
services:
  app_euroricambi_prod:
    build:
      args:
        user: eurodocker
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: euroricambi
    container_name: euroricambi-app-prod
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - euroricambi-network-prod

  db_euroricambi_prod:
    image: mysql:8.0
    container_name: euroricambi-db-prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - euroricambi-network-prod

  nginx:
    image: nginx:alpine
    container_name: euroricambi-nginx-prod
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - euroricambi-network-prod

networks:
  euroricambi-network-prod:
    driver: bridge