version: '3.7'
services:

  #PHP Service
  app_euroricambi_prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: euroricambidiesel.com/php
    container_name: app_euroricambi_prod
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app_euroricambi_prod
      SERVICE_TAGS: prod
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network-euroricambi-prod

  #Nginx Service
  webserver_euroricambi_prod:
    image: nginx:alpine
    container_name: webserver_euroricambi_prod
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - app-network-euroricambi-prod
    depends_on:
      - app_euroricambi_prod

  #MySQL Service
  db_euroricambi_prod:
    image: mysql:5.7.22
    container_name: db_euroricambi_prod
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: prod
      SERVICE_NAME: db_euroricambi_prod
    networks:
      - app-network-euroricambi-prod

#Docker Networks
networks:
  app-network-euroricambi-prod:
    driver: bridge
